version: '3'

services:
    db:
        image: mysql:5.7
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootwordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        volumes:
            - db-data:/var/lib/mysql
            
    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - "8001:80"
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - ./wordpress:/var/www/html/wp-content/ 

    phpadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        
volumes:
    db-data: {}
